### PR TITLE
Create nourhen-amdouni.pub

### PR DESCRIPTION
**Pull request by Nour19am**

### CODE REVIEW

**Comment by d9w** [comment]
There is a `~` at the end of your email in the key, please verify that this corresponds to your public key file.

**Comment by Nour19am** [comment]
yes

**Comment by Nour19am** [comment]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILEZrqgH3XO41+Tnho0z1e26y8HHp/kIW6BHzTGETWRB nourhene.amdounii@gmail.com~

**Review by Nour19am — COMMENTED** [review]
updated the pub key

**Pull request merged**
